# Generated by Django 2.2.2 on 2019-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.IntegerField(blank=True, max_length=256, null=True, verbose_name='этаж'),
        ),
    ]
